### ISSUE TITLE
Oudated DevDependency "chromedriver": "^2.45.0"

### ISSUE THREAD

**Issue by AllieHope** [webdriverio-community/wdio-chromedriver-service#26]
"chromedriver": "*" is correctly listed in peerDependencies, however "chromedriver": "^2.45.0" is also listed in devDependencies causing an error that "Chrome version must be between 71 and 75" even though in the most recent chromedriver the most recent version of Chrome is accepted.

**Comment by jbterry** [comment]
@AllieHope since this service is just a wrapper around whatever chromedriver version you have in your own projects package.json, this should not be an issue (i.e. you should not get the breaking error you shared about versions between 71 -> 75) as long as your projects own package references a more recent version of chromedriver. i had this issue myself and just updated my own projects (wdio) package.json to fetch chromedriver 76.0.0 from 2.46 and it worked perfectly

**Comment by christian-bromann** [comment]
It is recommended to maintain the `chromedriver` version yourself, which is why it is only a peerDependency of this service.
